(()=>{if(window.__fcNotDoneSync)return;window.__fcNotDoneSync=true;const clean=v=>String(v??'').replace(/\s+/g,' ').trim(),norm=v=>clean(v).toLowerCase();
function captureDashboard(){const panel=document.querySelector('#p-notvisited')||[...document.querySelectorAll('.panel')].find(x=>/not done|لم تتم الزيارة/i.test(x.textContent));if(!panel)throw Error('افتح تبويب Not Done في الداشبورد أولًا.');const table=panel.querySelector('table');if(!table)throw Error('حمّل ملف الأداء وانتظر ظهور جدول Not Done.');const th=[...table.querySelectorAll('thead th')].map(x=>norm(x.textContent)),idx=(...n)=>th.findIndex(x=>n.some(v=>x.includes(norm(v))));const ip=idx('ptid'),ipa=idx('patient'),idoc=idx('doctor','طبيب'),idrP=idx('dr p','drp'),idrD=idx('dr d','drd');if(ip<0||idoc<0)throw Error('لم يتم العثور على أعمدة PTID والطبيب.');const cases=[...table.querySelectorAll('tbody tr')].map(tr=>{const c=[...tr.cells].map(x=>clean(x.textContent));return{ptid:c[ip],patient:c[ipa]||'',doctor:c[idoc]||'Unassigned',drp:Number(c[idrP]||0),drd:Number(c[idrD]||0)}}).filter(x=>x.ptid&&x.drp>0&&x.drd===0);return [...new Map(cases.map(x=>[`${x.ptid}|${x.doctor}`,x])).values()]}
function patientCards(){return [...document.querySelectorAll('div.p-4')].filter(x=>x.offsetParent!==null&&/PTID\s+\d+\s+·/i.test(clean(x.textContent)))}
function cardPtid(card){return clean(card.textContent).match(/PTID\s+(\d+)\s+·/i)?.[1]||''}
function gpBlock(card){return [...card.querySelectorAll('div.rounded-xl')].find(x=>clean(x.querySelector('.font-semibold')?.textContent).toUpperCase()==='GP')}
function systemOptions(){const native=[...document.querySelectorAll('select option')].map(x=>clean(x.textContent)).filter(Boolean);const roles=[...document.querySelectorAll('[role=option]')].map(x=>clean(x.textContent)).filter(Boolean);return [...new Set([...native,...roles])]}
async function selectReason(card,reason,save){const block=gpBlock(card);if(!block)return{ok:false,error:'قسم GP غير موجود للمريض'};const trigger=block.querySelector('button[role=combobox]');if(!trigger)return{ok:false,error:'السبب محفوظ مسبقًا أو قائمة GP غير متاحة'};trigger.click();await new Promise(r=>setTimeout(r,180));const options=[...document.querySelectorAll('[role=option]')].filter(x=>x.offsetParent!==null),opt=options.find(x=>norm(x.textContent)===norm(reason));if(!opt){document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));return{ok:false,error:'السبب غير مطابق لقائمة iCare'}}opt.click();await new Promise(r=>setTimeout(r,180));if(save){const fresh=patientCards().find(x=>cardPtid(x)===cardPtid(card)),gp=fresh&&gpBlock(fresh),button=[...(gp?.querySelectorAll('button')||[])].find(x=>clean(x.textContent)==='حفظ');if(!button)return{ok:false,error:'تم اختيار السبب لكن زر الحفظ غير موجود'};button.click();await new Promise(r=>setTimeout(r,350))}return{ok:true}}
async function applyReasons(items,dryRun){const pending=new Map(items.filter(x=>!x.error).map(x=>[String(x.ptid).replace(/\D/g,''),x])),log=[],seen=new Set();let pages=0,totalCards=0;while(pages++<20){const cards=patientCards();totalCards+=cards.length;for(const card of cards){const ptid=cardPtid(card),item=pending.get(ptid);if(!item||seen.has(ptid))continue;seen.add(ptid);const gp=gpBlock(card);if(!gp){log.push({...item,status:'Skipped',error:'قسم GP غير موجود'});continue}const combo=gp.querySelector('button[role=combobox]');if(!combo){log.push({...item,status:'Skipped',error:'يوجد سبب محفوظ مسبقًا أو لا توجد قائمة تعديل'});continue}if(dryRun){log.push({...item,status:'Ready'});continue}const res=await selectReason(card,item.reason,true);log.push({...item,status:res.ok?'Saved':'Skipped',error:res.error||''})}
 const next=[...document.querySelectorAll('button')].find(x=>clean(x.textContent)==='التالي');if(!next||next.disabled)break;const first=cards[0]&&cardPtid(cards[0]);next.click();for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,150));const now=patientCards()[0]&&cardPtid(patientCards()[0]);if(now&&now!==first)break}}
 if(dryRun){const firstButton=[...document.querySelectorAll('button')].find(x=>clean(x.textContent)==='الأولى'&&!x.disabled);if(firstButton){firstButton.click();await new Promise(r=>setTimeout(r,400))}}
 for(const [ptid,item]of pending)if(!seen.has(ptid))log.push({...item,status:'Skipped',error:'PTID غير موجود في صفحات النتائج الحالية'});return{log,options:systemOptions(),visibleRows:totalCards,pages:pages}}
chrome.runtime.onMessage.addListener((m,s,send)=>{(async()=>{if(m.type==='CAPTURE')return{cases:captureDashboard()};if(m.type==='APPLY')return applyReasons(m.items,m.dryRun);throw Error('Unknown content action')})().then(x=>send({ok:true,...x})).catch(e=>send({ok:false,error:e.message}));return true});})();
