const $=id=>document.getElementById(id),msg=(id,t,bad=false)=>{const e=$(id);e.textContent=t;e.className=`info ${bad?'bad':'good'}`};let reviewed=[];
const active=()=>new Promise(r=>chrome.tabs.query({active:true,currentWindow:true},x=>r(x[0])));const sendTab=async m=>{const t=await active();return chrome.tabs.sendMessage(t.id,m)};const send=m=>chrome.runtime.sendMessage(m);
const text=v=>String(v??'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim(),norm=v=>text(v).toLowerCase().replace(/[._-]+/g,' ').replace(/\s+/g,' '),number=v=>{const n=Number(String(v??'').replace(/,/g,'').trim());return Number.isFinite(n)?n:0};
function pick(row,...names){for(const name of names){const key=Object.keys(row).find(k=>norm(k)===norm(name));if(key!==undefined)return row[key]}return''}
function htmlWorkbookRows(ab){const bytes=new Uint8Array(ab),enc=bytes[0]===255&&bytes[1]===254?'utf-16le':'utf-8',source=new TextDecoder(enc).decode(bytes);if(!/<html|<table/i.test(source.slice(0,5000)))return[];const doc=new DOMParser().parseFromString(source,'text/html'),out=[];for(const [ti,table]of [...doc.querySelectorAll('table')].entries()){const rows=[...table.querySelectorAll('tr')].map(tr=>[...tr.children].filter(x=>/^(TD|TH)$/.test(x.tagName)).map(x=>text(x.textContent)));const hi=rows.findIndex(r=>r.some(x=>norm(x)==='ptid')&&r.some(x=>norm(x)==='dr p'));if(hi<0)continue;const headers=rows[hi],data=rows.slice(hi+1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));out.push({name:`HTML Table ${ti+1}`,data,score:headers.filter(k=>['ptid','patient name','doctor name','dr p','dr d'].includes(norm(k))).length})}return out}
async function importExcel(file){if(typeof XLSX==='undefined')throw Error('قارئ Excel غير متاح. أعد تحميل الإضافة.');const ab=await file.arrayBuffer(),htmlCandidates=htmlWorkbookRows(ab),candidates=[...htmlCandidates];if(!htmlCandidates.length){const wb=XLSX.read(ab,{type:'array',cellDates:true});for(const name of wb.SheetNames){const data=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:false});if(data.length)candidates.push({name,data,score:Object.keys(data[0]||{}).filter(k=>['ptid','patient name','doctor name','dr p','dr d'].includes(norm(k))).length})}}const best=candidates.sort((a,b)=>b.score-a.score||b.data.length-a.data.length)[0];if(!best||best.score<3)throw Error('لم يتم العثور على أعمدة PTID وDoctor Name وDR P وDR D.');let deactive=0;const cases=[];for(const row of best.data){const ptid=text(pick(row,'PTID','Patient ID','MRN')),status=norm(pick(row,'Status','Patient Status')).replace(/[^a-z0-9\u0600-\u06ff]/g,''),drp=number(pick(row,'DR P','DR Plan')),drd=number(pick(row,'DR D','DR Done'));if(!ptid)continue;if(['deactive','deactivated','inactive'].includes(status)){deactive++;continue}if(drp>0&&drd===0)cases.push({ptid,patient:text(pick(row,'Patient Name','Patient')),doctor:text(pick(row,'Doctor Name','Doctor','Staff Name'))||'Unassigned',drp,drd})}const unique=[...new Map(cases.map(x=>[`${x.ptid}|${x.doctor}`,x])).values()];if(!unique.length)throw Error('لا توجد حالات تحقق DRP>0 وDRD=0 بعد استبعاد Deactive.');await chrome.storage.local.set({capturedCases:unique,sourceFile:{name:file.name,sheet:best.name,importedAt:new Date().toISOString(),deactive}});msg('fileInfo',`${file.name}\n${unique.length} مريض Not Done — ${new Set(unique.map(x=>x.doctor)).size} طبيب\nDeactive مستبعد: ${deactive}`);msg('captureInfo',`${unique.length} مريض Not Done محفوظ من Excel`);return unique}
const drop=$('excelDrop'),fileInput=$('excelFile');['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)importExcel(f).catch(x=>msg('fileInfo',x.message,true))});fileInput.addEventListener('change',()=>{const f=fileInput.files?.[0];if(f)importExcel(f).catch(x=>msg('fileInfo',x.message,true))});
async function refresh(){const r=await send({type:'GET_STATE'});const c=r.data?.capturedCases||[],s=r.data?.doctorSheets||[];msg('captureInfo',c.length?`${c.length} مريض Not Done محفوظ — ${new Set(c.map(x=>x.doctor)).size} طبيب`:'لا توجد حالات محفوظة.');$('links').innerHTML=s.map(x=>`<div class="doctor"><b>${x.title||x.doctor||'ملف جميع الأطباء'}</b><br>${x.doctorCount?`${x.doctorCount} طبيب — `:''}${x.count} مريض<br><a href="${x.url}" target="_blank">فتح رابط التحرير الواحد</a> · <a href="${x.xlsxUrl||x.url}" target="_blank">تنزيل Excel الكامل</a></div>`).join('')}
$('capture').onclick=async()=>{try{const r=await sendTab({type:'CAPTURE'});if(!r.ok)throw Error(r.error);await chrome.storage.local.set({capturedCases:r.cases});msg('captureInfo',`${r.cases.length} مريض Not Done — ${new Set(r.cases.map(x=>x.doctor)).size} طبيب`)}catch(e){msg('captureInfo',e.message,true)}};
$('create').onclick=async()=>{const b=$('create');try{b.disabled=true;const {capturedCases=[]}=await chrome.storage.local.get('capturedCases');if(!capturedCases.length)throw Error('التقط حالات Not Done أولًا.');const r=await send({type:'CREATE_SHEETS',cases:capturedCases});if(!r.ok)throw Error(r.error);await refresh()}catch(e){msg('captureInfo',e.message,true)}finally{b.disabled=false}};
$('review').onclick=async()=>{try{const r=await send({type:'READ_SHEETS'});if(!r.ok)throw Error(r.error);reviewed=r.data.filter(x=>!x.error);const t=await sendTab({type:'APPLY',items:reviewed,dryRun:true});if(!t.ok)throw Error(t.error);const ready=t.log.filter(x=>x.status==='Ready').length,skip=t.log.length-ready;msg('syncInfo',`جاهز: ${ready} | متوقف للمراجعة: ${skip} | صفوف الصفحة: ${t.visibleRows}\nخيارات النظام الظاهرة: ${t.options.join('، ')||'تظهر بعد فتح القائمة'}`,skip>0)}catch(e){msg('syncInfo',e.message,true)}};
$('apply').onclick=async()=>{try{if(!reviewed.length)throw Error('اضغط مراجعة الأسباب أولًا.');if(!confirm(`سيتم إدخال وحفظ أسباب ${reviewed.length} حالة داخل iCare حسب PTID وفي قسم GP فقط، مع الانتقال بين صفحات النتائج. هل تريد المتابعة؟`))return;const r=await sendTab({type:'APPLY',items:reviewed,dryRun:false});if(!r.ok)throw Error(r.error);const ok=r.log.filter(x=>x.status==='Saved').length,skip=r.log.length-ok;const sync=await send({type:'UPDATE_SYNC_RESULTS',results:r.log});await chrome.storage.local.set({lastSyncLog:r.log,lastSyncAt:new Date().toISOString()});msg('syncInfo',`تم الحفظ داخل iCare: ${ok} | لم يُحفظ: ${skip} | تم تحديث Google Sheets: ${sync.data?.updated||0} | الصفحات المفحوصة: ${r.pages}`,skip>0)}catch(e){msg('syncInfo',e.message,true)}};
$('settings').onclick=()=>chrome.runtime.openOptionsPage();refresh();
